### ISSUE TITLE
Goals not appearing on mobile

### ISSUE THREAD

**Issue by MaxTheSpy** [lynchjames/obsidian-writing-goals#56]
Word goals do not appear on mobile in the side panel when pulled up. The only way to access the word goals is to open the goals in a new page using the command pallet.

Would be nice if this was worked out. Im not sure if its an obsidian issue or this plugins issue or what, but I wanted to bring it up since I work primarily on tablet.

**Comment by Azmoinal** [comment]
I think that has been broken by obsidian 1.6 since it was working on previous versions.

**Comment by Medullitus** [comment]
Is the developer looking here?? I'm getting a 'FAILED TO SHOW GOAL' error!!

**Comment by Medullitus** [comment]
![Obsidian_pUEAedQ8il](https://github.com/lynchjames/obsidian-writing-goals/assets/52373851/030b9ab4-2a98-4574-be20-86483a34295d)

**Comment by Medullitus** [comment]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'dailyGoalCount')
    at create_fragment$2 (plugin:writing-goals:4151:33)
    at init (plugin:writing-goals:1018:34)
    at new Simple_goal (plugin:writing-goals:4359:3)
    at FileLabels.createSimpleGoal (plugin:writing-goals:4392:9)
    at eval (plugin:writing-goals:4386:26)
    at Array.forEach (<anonymous>)
    at FileLabels.initFileLabels (plugin:writing-goals:4378:21)
    at WritingGoals.loadNoteGoalData (plugin:writing-goals:22341:29)
    at async GoalModal.onSubmit (plugin:writing-goals:20584:9)
create_fragment$2 @ plugin:writing-goals:4151
init @ plugin:writing-goals:1018
Simple_goal @ plugin:writing-goals:4359
createSimpleGoal @ plugin:writing-goals:4392
eval @ plugin:writing-goals:4386
initFileLabels @ plugin:writing-goals:4378
loadNoteGoalData @ plugin:writing-goals:22341

**Comment by Medullitus** [comment]
> I think that has been broken by obsidian 1.6 since it was working on previous versions.

Heyy. Are you there??

**Comment by Medullitus** [comment]
UPDATE: I found the issue! The HOMEPAGE plugin

When the Homepage plugin is enabled, the daily word goal plugin doesn't open and gives an error. You can disable the Homepage plugin, open the word goal window, and then reactivate the Homepage plugin. Thanks. @ssa we love you and your plugin is amazing! Please don't leave us!! Thanks <3<3<3<3<3

**Comment by Azmoinal** [comment]
I noticed that writing goals disappeared also on the sidebar on desktop version.

Goals are still available in the file explorer and into the dedicated page listing all goals.

**Comment by lynchjames** [comment]
@Azmoinal could you raise a separate issue for the desktop issue with the plugin version you're using?

**Comment by Azmoinal** [comment]
> @Azmoinal could you raise a separate issue for the desktop issue with the plugin version you're using?

Hi, I didn't noticed the latest releases of the plugin so I updated it on both desktop and mobile.

After the update, I'm able to open the right panel on both iPad and Windows Obsidian app so the point could be closed for me. 

P.S. It is not related to this issue but I noticed also a big improvement in managing folders. I've a vault with 5k files and I added a goal on a folder with 250 files and I didn't observe any lag anymore. Thanks a lot for your work!

**Comment by Azmoinal** [comment]
I’ve updated the plugin to the latest 0.10.7 and it seems that, at least on mobile (iPad), it is completely broken. 

I cannot see anymore the goals into the explorer neither in the right sidebar. The element in the right sidebar is here but it is empty.

Also the full “Writing Goal Stats” is completely blank. It seems that something is not loading or it is not able to render the progress at all but the plugin seems available. 

I tried to uninstall/reinstall the plugin but without any success.

Let me know how I could help

**Comment by Azmoinal** [comment]
@lynchjames  I found two errors:

Log: \["Writing Goals: error reading JSON file at ",".obsidian/plugins/writing-goals/goal-history.json"]
Fatal: Uncaught (in promise) goalItemForDate@@

**Comment by grimborg** [comment]
Still broken for me: latest Writing Goals 0.10.7 and Obsidian 1.6.7 on iPad. The goals sidebar is empty, trying to add or update goals through the plugin does nothing (I can enter the values, but it doesn’t modify the file), and “view all your writing goals stats” shows an empty page. The sprint goal does show, though.

Tested also on a brand new vault without any other plugins, same result.

Thanks!

**Comment by Azmoinal** [comment]
My cent: I tried to remove the plugin and to reinstall it from scratch and I observed the same behaviour described by @grimborg. After that, I restored a previous version of the goal-history.json and voila, everything started to work fine.

So, my guess is that there is something wrong with the management of the goal-history.json that it seems that is not properly filled when the plugin find it empty.

I don't know if it could help.

@grimborg could you check if the file is properly structured? In my case during a merge using gir, working copy app added two lines that broke it syntax leading to the same error.

**Comment by grimborg** [comment]
Thanks for the idea, but it doesn't look like this is what's causing it. `goal-history.json` is well formed. This is what it's like now, and it works on desktop but not on ipad:

`$ cat goal-history.json
{
  "Diari/2024-08-11.md": [
    {
      "dailyGoal": 10,
      "goal": 30,
      "startCount": 7,
      "endCount": 7,
      "date": "Sun Aug 11 2024 00:00:00 GMT+0200"
    }
  ]
}`
